image: node:latest

before_script:
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages:
   - build
   - test
   - deploy 

build:
   stage: build
   script:
    - npm install
   except:
    - develop
    - master

test:
  stage: test
  script:
   - echo "Insert test here"
  except:
   - develop
   - master


deployment:
  stage: deploy
  script:
  - npm install
  - apt-get update && apt-get install rsync -y
  - sleep 0.1
  - bash ./deliver.sh

  only: 
    - develop
    - master
